// <auto-generated />
using System;
using DataAcessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAcessLayer.Migrations
{
    [DbContext(typeof(CIPToolContext))]
    [Migration("20210323195133_AddedMissingForeignKeys")]
    partial class AddedMissingForeignKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BusinessObjectLayer.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.BonusCorrectionFactorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("CorrectionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BonusCorrectionFactors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectionFactor = 1m,
                            Text = "never discussed in the organization"
                        },
                        new
                        {
                            Id = 2,
                            CorrectionFactor = 0.5m,
                            Text = "previously discussed in the organization"
                        });
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.BonusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BonusCorrectionFactorId")
                        .HasColumnType("int");

                    b.Property<int>("BonusRangeId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BonusCorrectionFactorId");

                    b.HasIndex("BonusRangeId");

                    b.HasIndex("FinancialReportId")
                        .IsUnique()
                        .HasFilter("[FinancialReportId] IS NOT NULL");

                    b.ToTable("Bonuses");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.BonusRangeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Award")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LowerBound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UpperBound")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BonusRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Award = 0.0m,
                            LowerBound = -10000000.0m,
                            UpperBound = 500.0m
                        },
                        new
                        {
                            Id = 2,
                            Award = 50.0m,
                            LowerBound = 500.0m,
                            UpperBound = 1000.0m
                        },
                        new
                        {
                            Id = 3,
                            Award = 90.0m,
                            LowerBound = 1000.0m,
                            UpperBound = 2000.0m
                        },
                        new
                        {
                            Id = 4,
                            Award = 160.0m,
                            LowerBound = 2000.0m,
                            UpperBound = 3000.0m
                        },
                        new
                        {
                            Id = 5,
                            Award = 300.0m,
                            LowerBound = 3000.0m,
                            UpperBound = 6000.0m
                        },
                        new
                        {
                            Id = 6,
                            Award = 300.0m,
                            LowerBound = 6000.0m,
                            UpperBound = 10000.0m
                        },
                        new
                        {
                            Id = 7,
                            Award = 500.0m,
                            LowerBound = 10000.0m,
                            UpperBound = 20000.0m
                        },
                        new
                        {
                            Id = 8,
                            Award = 900.0m,
                            LowerBound = 20000.0m,
                            UpperBound = 30000.0m
                        },
                        new
                        {
                            Id = 9,
                            Award = 1100.0m,
                            LowerBound = 30000.0m,
                            UpperBound = 40000.0m
                        },
                        new
                        {
                            Id = 10,
                            Award = 1200.0m,
                            LowerBound = 40000.0m,
                            UpperBound = 50000.0m
                        },
                        new
                        {
                            Id = 11,
                            Award = 1500.0m,
                            LowerBound = 50000.0m,
                            UpperBound = 10000000.0m
                        });
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.FinancialReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActualExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActualSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BonusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlannedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlannedExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlannedSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId")
                        .IsUnique()
                        .HasFilter("[IdeaId] IS NOT NULL");

                    b.ToTable("FinancialReports");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.IdeaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssociateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DoDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdeaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAssociateResponsible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RichTextDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociateId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.IdeaStatusEntity", b =>
                {
                    b.Property<Guid?>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdeaId", "StatusId");

                    b.HasIndex("StatusId");

                    b.ToTable("IdeaStatuses");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.LeaderResponse", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LeaderResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Response")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("LeaderResponses");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.StatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("CategoryIdeaEntity", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<Guid>("IdeasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "IdeasId");

                    b.HasIndex("IdeasId");

                    b.ToTable("CategoryIdeaEntity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.Associate", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaderId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("LeaderId");

                    b.HasDiscriminator().HasValue("Associate");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.Leader", b =>
                {
                    b.HasBaseType("BusinessObjectLayer.Entities.Associate");

                    b.HasDiscriminator().HasValue("Leader");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.Attachment", b =>
                {
                    b.HasOne("BusinessObjectLayer.Entities.IdeaEntity", "Idea")
                        .WithMany("Attachments")
                        .HasForeignKey("IdeaId");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.BonusEntity", b =>
                {
                    b.HasOne("BusinessObjectLayer.Entities.BonusCorrectionFactorEntity", "BonusCorrectionFactor")
                        .WithMany()
                        .HasForeignKey("BonusCorrectionFactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjectLayer.Entities.BonusRangeEntity", "BonusRange")
                        .WithMany()
                        .HasForeignKey("BonusRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjectLayer.Entities.FinancialReportEntity", "FinancialReport")
                        .WithOne("Bonus")
                        .HasForeignKey("BusinessObjectLayer.Entities.BonusEntity", "FinancialReportId");

                    b.Navigation("BonusCorrectionFactor");

                    b.Navigation("BonusRange");

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.FinancialReportEntity", b =>
                {
                    b.HasOne("BusinessObjectLayer.Entities.IdeaEntity", "Idea")
                        .WithOne("FinancialReport")
                        .HasForeignKey("BusinessObjectLayer.Entities.FinancialReportEntity", "IdeaId");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.IdeaEntity", b =>
                {
                    b.HasOne("BusinessObjectLayer.Entities.Associate", "Associate")
                        .WithMany("Ideas")
                        .HasForeignKey("AssociateId");

                    b.HasOne("BusinessObjectLayer.Entities.Associate", "Reviewer")
                        .WithMany("IdeasToReview")
                        .HasForeignKey("ReviewerId");

                    b.Navigation("Associate");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.IdeaStatusEntity", b =>
                {
                    b.HasOne("BusinessObjectLayer.Entities.IdeaEntity", "Idea")
                        .WithMany("ApprovalStatuses")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjectLayer.Entities.StatusEntity", "Status")
                        .WithMany("ApprovalStatuses")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.LeaderResponse", b =>
                {
                    b.HasOne("BusinessObjectLayer.Entities.IdeaEntity", "Idea")
                        .WithMany("LeaderResponses")
                        .HasForeignKey("IdeaId");

                    b.HasOne("BusinessObjectLayer.Entities.Associate", "Reviewer")
                        .WithMany("Responses")
                        .HasForeignKey("ReviewerId");

                    b.Navigation("Idea");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("CategoryIdeaEntity", b =>
                {
                    b.HasOne("BusinessObjectLayer.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjectLayer.Entities.IdeaEntity", null)
                        .WithMany()
                        .HasForeignKey("IdeasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.Associate", b =>
                {
                    b.HasOne("BusinessObjectLayer.Entities.Leader", "Leader")
                        .WithMany("Associates")
                        .HasForeignKey("LeaderId");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.FinancialReportEntity", b =>
                {
                    b.Navigation("Bonus");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.IdeaEntity", b =>
                {
                    b.Navigation("ApprovalStatuses");

                    b.Navigation("Attachments");

                    b.Navigation("FinancialReport");

                    b.Navigation("LeaderResponses");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.StatusEntity", b =>
                {
                    b.Navigation("ApprovalStatuses");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.Associate", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("IdeasToReview");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("BusinessObjectLayer.Entities.Leader", b =>
                {
                    b.Navigation("Associates");
                });
#pragma warning restore 612, 618
        }
    }
}
